### PR TITLE
upgrade webtau to 1.16

### PR DESCRIPTION
**Pull request by MykolaGolubyev**

### CODE REVIEW

**Comment by MykolaGolubyev** [comment]
@byc1234 could you please make me a favor and try to locally build this branch? I am confused as to what is going on :(

**Comment by byc1234** [comment]
I will try now.

**Comment by byc1234** [comment]
Linux failed to build.

Results :

Failed tests:   should report invalid links urls(com.twosigma.znai.diagrams.FlowChartIncludePluginTest): (..)

Tests in error: 
  should provide svg, styles and custom shapes as result(com.twosigma.znai.diagrams.graphviz.GraphvizEngineTest)
  should convert user provided links(com.twosigma.znai.diagrams.FlowChartIncludePluginTest): Could not initialize class com.twosigma.znai.diagrams.graphviz.Graphviz

Tests run: 18, Failures: 1, Errors: 2, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Znai ............................................... SUCCESS [  0.129 s]
[INFO] znai-utils-for-testing ............................. SUCCESS [  0.435 s]
[INFO] znai-utils ......................................... SUCCESS [  2.029 s]
[INFO] znai-console ....................................... SUCCESS [  1.048 s]
[INFO] znai-testing-tcli .................................. SUCCESS [  3.373 s]
[INFO] znai-testing-examples .............................. SUCCESS [  1.494 s]
[INFO] znai-core .......................................... SUCCESS [  3.439 s]
[INFO] znai-site-extensions ............................... SUCCESS [  0.061 s]
[INFO] znai-java .......................................... SUCCESS [  1.739 s]
[INFO] znai-groovy ........................................ SUCCESS [  3.767 s]
[INFO] znai-latex ......................................... SUCCESS [  0.032 s]
[INFO] znai-cpp ........................................... SUCCESS [  3.509 s]
[INFO] znai-open-api ...................................... SUCCESS [  1.526 s]
[INFO] znai-typescript .................................... SUCCESS [  9.703 s]
[INFO] znai-jupyter ....................................... SUCCESS [  0.101 s]
[INFO] znai-sphinx ........................................ SUCCESS [  1.485 s]
[INFO] znai-reactjs ....................................... SUCCESS [04:24 min]
[INFO] znai-diagrams ...................................... FAILURE [  1.871 s]
[INFO] znai ............................................... SKIPPED
[INFO] znai-server ........................................ SKIPPED
[INFO] znai-client ........................................ SKIPPED
[INFO] znai-cli ........................................... SKIPPED
[INFO] znai-maven-plugin .................................. SKIPPED
[INFO] znai-ddjt-docs ..................................... SKIPPED
[INFO] znai-ecmascript .................................... SKIPPED
[INFO] znai-reactjs-default-components .................... SKIPPED
[INFO] znai-generators .................................... SKIPPED
[INFO] znai-docs .......................................... SKIPPED
[INFO] znai-shaded ........................................ SKIPPED
[INFO] znai-dist .......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:01 min
[INFO] Finished at: 2019-12-16T16:35:01+00:00
[INFO] Final Memory: 136M/2684M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project znai-diagrams: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/hwansoo/znaigithub/znai-diagrams/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :znai-diagrams
hwansoo@lhs:~/znaigithub$

**Comment by MykolaGolubyev** [comment]
@byc1234 that's probably because you don't have graphviz installed on linux. I have test failures in CI and I can't reproduce them locally.

**Comment by byc1234** [comment]
I will try again with graphviz then and let you know.

**Comment by byc1234** [comment]
I have the same error like CI with a linux machine.

=====

should read table from json by detecting format(com.twosigma.znai.extensions.table.TableIncludePluginTest)  Time elapsed: 0.005 sec  <<< FAILURE!
java.lang.AssertionError: 
mismatches:

[value].table.data[0][0][0].type:   actual: "Paragraph" <java.lang.String>
                                  expected: "TestMarkup" <java.lang.String>
                                             ^
[value].table.data[0][1][0].type:   actual: "Paragraph" <java.lang.String>
                                  expected: "TestMarkup" <java.lang.String>
                                             ^
[value].table.data[0][2][0].type:   actual: "Paragraph" <java.lang.String>
                                  expected: "TestMarkup" <java.lang.String>
                                             ^
[value].table.data[1][0][0].type:   actual: "Paragraph" <java.lang.String>
                                  expected: "TestMarkup" <java.lang.String>
                                             ^
[value].table.data[1][1][0].type:   actual: "Paragraph" <java.lang.String>
                                  expected: "TestMarkup" <java.lang.String>
                                             ^
[value].table.data[1][2][0].type:   actual: "Paragraph" <java.lang.String>
                                  expected: "TestMarkup" <java.lang.String>
                                             ^

missing, but expected values:

[value].table.data[0][0][0].markup: "#12BGD3"
[value].table.data[0][1][0].markup: "100"
[value].table.data[0][2][0].markup: "custom table with a long attachment"
[value].table.data[1][0][0].markup: "#12BGD3"
[value].table.data[1][1][0].markup: "150"
[value].table.data[1][2][0].markup: "chair"

unexpected values:

[value].table.data[0][0][0].content: [{text=#12BGD3, type=SimpleText}]
[value].table.data[0][1][0].content: [{text=100, type=SimpleText}]
[value].table.data[0][2][0].content: [{text=custom table with a long attachment, type=SimpleText}]
[value].table.data[1][0][0].content: [{text=#12BGD3, type=SimpleText}]
[value].table.data[1][1][0].content: [{text=150, type=SimpleText}]
[value].table.data[1][2][0].content: [{text=chair, type=SimpleText}]
	at com.twosigma.webtau.expectation.ActualValue.handleMismatch(ActualValue.java:84)
	at com.twosigma.webtau.expectation.ActualValue.should(ActualValue.java:39)
	at com.twosigma.webtau.expectation.ActualValueExpectations$should.call(Unknown Source)
	at com.twosigma.webtau.data.expectation.ExpectationExtension.should(ExpectationExtension.groovy:26)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.metaclass.ReflectionMetaMethod.invoke(ReflectionMetaMethod.java:54)
	at org.codehaus.groovy.runtime.metaclass.NewInstanceMetaMethod.invoke(NewInstanceMetaMethod.java:54)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:244)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at com.twosigma.znai.extensions.table.TableIncludePluginTest.should read table from json by detecting format(TableIncludePluginTest.groovy:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running com.twosigma.znai.website.WebSiteDocStructureTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.017 sec
Running com.twosigma.znai.website.WebSiteUserExtensionsTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.016 sec
Running com.twosigma.znai.website.markups.MarkupParsingConfigurationsTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.02 sec
Running com.twosigma.znai.structure.DocMetaTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec

Results :

Failed tests:   should create markdown code snippets and result as one doc element(com.twosigma.znai.extensions.markup.MarkdownAndResultFencePluginTest): (..)
  should pick first available file to include(com.twosigma.znai.extensions.markup.MarkdownIncludePluginTest): (..)
  should filter out columns from json based on case insensitive provided names(com.twosigma.znai.extensions.table.TableIncludePluginTest): (..)
  should filter out columns from csv based on case insensitive provided names(com.twosigma.znai.extensions.table.TableIncludePluginTest): (..)
  should read table from json by detecting format(com.twosigma.znai.extensions.table.TableIncludePluginTest): (..)

Tests run: 44, Failures: 5, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Znai ............................................... SUCCESS [  0.121 s]

**Comment by MykolaGolubyev** [comment]
Thank you @byc1234. Will try to figure it out it later. Wonder if it is hash maps or something like that. Tests pass on Mac in maven and IDE.

**Pull request merged**
