### PR TITLE
CustomHandler can override all of methods instead of accepting only GET

### PR DESCRIPTION
**Pull request by byc1234**

### CODE REVIEW

**Comment by byc1234** [comment]
I use POST to backend instead of GET to accumulate tracking info. 
The handler can't process any rest api if `RoutingContext` is not available.
If we don't want to pass `RoutingContext`, we need to implement api handling in `DocumentationServer` explicitly. That's what you were against.

**Comment by MykolaGolubyev** [comment]
Alternatively we could expand the handlers interface to let implementors explicitly choose which one they want to implement. 
Interface would have get post put delete methods.
Query params can be passed as a map or a wrapper class that has nothing to do with vertx.

**Comment by byc1234** [comment]
We also need to pass headers and body.
If a user wants to implement the similar function of code as in `DocumentationUploadHandler`, the code should be in `DocumenationServer` regardless the api is only required for a specific user.

**Comment by MykolaGolubyev** [comment]
On a second thought if it is for tracking purposes I think it will be better to send the tracking request to a dedicated tracking server, not the doc server.

**Comment by MykolaGolubyev** [comment]
UrlHandlers role was to serve an additional content.

**Comment by byc1234** [comment]
We do have a dedicated service to track events. But Access-Origin should be the same one.

**Pull request closed without merging**
